import 'package:flutter/material.dart';

class CategoryVisuals {
  const CategoryVisuals._();

  static const List<int> palette = <int>[
    0xFF115E59,
    0xFFD97706,
    0xFF1D4ED8,
    0xFFBE185D,
    0xFF7C3AED,
    0xFF0F766E,
    0xFFB91C1C,
    0xFF059669,
    0xFF2563EB,
    0xFF9333EA,
    0xFFDB2777,
    0xFFCA8A04,
    0xFFEA580C,
    0xFF0891B2,
    0xFF4F46E5,
    0xFF16A34A,
    0xFFDC2626,
    0xFFA16207,
    0xFF0D9488,
    0xFF6D28D9,
    0xFFC026D3,
    0xFF0284C7,
    0xFF65A30D,
    0xFFEF4444,
  ];

  static const Map<String, IconData> iconMap = <String, IconData>{
    'category': Icons.category_rounded,
    'shopping': Icons.shopping_basket_rounded,
    'cart': Icons.shopping_cart_rounded,
    'store': Icons.storefront_rounded,
    'bag': Icons.shopping_bag_rounded,
    'gift': Icons.card_giftcard_rounded,
    'car': Icons.directions_car_filled_rounded,
    'gas': Icons.local_gas_station_rounded,
    'bus': Icons.directions_bus_rounded,
    'train': Icons.train_rounded,
    'flight': Icons.flight_rounded,
    'taxi': Icons.local_taxi_rounded,
    'parking': Icons.local_parking_rounded,
    'home': Icons.home_rounded,
    'rent': Icons.house_rounded,
    'utilities': Icons.lightbulb_rounded,
    'repair': Icons.build_rounded,
    'wifi': Icons.wifi_rounded,
    'health': Icons.health_and_safety_rounded,
    'doctor': Icons.medical_services_rounded,
    'pharmacy': Icons.local_pharmacy_rounded,
    'fitness': Icons.fitness_center_rounded,
    'heart': Icons.favorite_rounded,
    'restaurant': Icons.restaurant_rounded,
    'groceries': Icons.local_grocery_store_rounded,
    'coffee': Icons.coffee_rounded,
    'fastfood': Icons.fastfood_rounded,
    'delivery': Icons.delivery_dining_rounded,
    'salary': Icons.payments_rounded,
    'wallet': Icons.account_balance_wallet_rounded,
    'bank': Icons.account_balance_rounded,
    'savings': Icons.savings_rounded,
    'investment': Icons.trending_up_rounded,
    'debt': Icons.credit_card_rounded,
    'loan': Icons.request_quote_rounded,
    'money': Icons.attach_money_rounded,
    'bonus': Icons.emoji_events_rounded,
    'refund': Icons.assignment_return_rounded,
    'work': Icons.work_rounded,
    'office': Icons.business_center_rounded,
    'software': Icons.computer_rounded,
    'laptop': Icons.laptop_mac_rounded,
    'phone': Icons.phone_android_rounded,
    'electronics': Icons.devices_rounded,
    'beauty': Icons.face_retouching_natural_rounded,
    'skincare': Icons.spa_rounded,
    'hair': Icons.content_cut_rounded,
    'family': Icons.family_restroom_rounded,
    'kids': Icons.child_friendly_rounded,
    'pets': Icons.pets_rounded,
    'travel': Icons.luggage_rounded,
    'hotel': Icons.hotel_rounded,
    'beach': Icons.beach_access_rounded,
    'map': Icons.map_rounded,
    'movie': Icons.movie_rounded,
    'music': Icons.music_note_rounded,
    'game': Icons.sports_esports_rounded,
    'sports': Icons.sports_soccer_rounded,
    'book': Icons.menu_book_rounded,
    'school': Icons.school_rounded,
    'subscription': Icons.subscriptions_rounded,
    'internet': Icons.language_rounded,
    'insurance': Icons.shield_rounded,
    'security': Icons.security_rounded,
    'charity': Icons.volunteer_activism_rounded,
    'petsupplies': Icons.pets_rounded,
    'event': Icons.celebration_rounded,
    'calendar': Icons.event_note_rounded,
    'camera': Icons.camera_alt_rounded,
    'photo': Icons.photo_camera_rounded,
    'tools': Icons.handyman_rounded,
    'cleaning': Icons.cleaning_services_rounded,
    'laundry': Icons.local_laundry_service_rounded,
    'education': Icons.cast_for_education_rounded,
    'tax': Icons.receipt_long_rounded,
    'fees': Icons.sell_rounded,
    'cash': Icons.payments_rounded,
    'uncategorized': Icons.more_horiz_rounded,
  };

  static Color colorFromValue(int colorValue) => Color(colorValue);

  static IconData iconFromKey(String key) =>
      iconMap[key] ?? Icons.category_rounded;
}
